---
label: Hugo, Forestry & Netlifyでブログを作成
hide_body: true
display_field: tekk_blog
fields:
- name: tekk_blog
  type: text
  config:
    required: false
  hidden: false
  label: Tekk Blog
- name: fywyrerweyrywuywuwherwgrewgwergwegwreyreywrywywrywywywwre
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: fywyrerweyrywuywuwherwgrewgwergwegwreyreywrywywrywywywwre
pages:
- content/posts/sample.md
